<?php
/**
 * reparation - Succursal.php
 * Create by ALCINDOR LOSTHELVEN
 * Created on: 8/20/2020
 */

namespace app\DefaultApp\Models;


use systeme\Model\Model;

class Succursal extends Model
{

    private $id,$nom,$addresse,$telephone;
    private $id_agent,$id_departement,$id_ville,$photo,$longitude,$latitude;

    /**
     * @return mixed
     */
    public function getIdAgent()
    {
        return $this->id_agent;
    }

    /**
     * @param mixed $id_agent
     */
    public function setIdAgent($id_agent)
    {
        $this->id_agent = $id_agent;
    }

    /**
     * @return mixed
     */
    public function getIdDepartement()
    {
        return $this->id_departement;
    }

    /**
     * @param mixed $id_departement
     */
    public function setIdDepartement($id_departement)
    {
        $this->id_departement = $id_departement;
    }

    /**
     * @return mixed
     */
    public function getIdVille()
    {
        return $this->id_ville;
    }

    /**
     * @param mixed $id_ville
     */
    public function setIdVille($id_ville)
    {
        $this->id_ville = $id_ville;
    }

    /**
     * @return mixed
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * @param mixed $photo
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;
    }

    /**
     * @return mixed
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * @param mixed $longitude
     */
    public function setLongitude($longitude)
    {
        $this->longitude = $longitude;
    }

    /**
     * @return mixed
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * @param mixed $latitude
     */
    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;
    }


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getAddresse()
    {
        return $this->addresse;
    }

    /**
     * @param mixed $adresse
     */
    public function setAddresse($addresse)
    {
        $this->addresse = $addresse;
    }

    /**
     * @return mixed
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * @param mixed $telephone
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;
    }

    private function existe($nom)
    {
        $con = self::connection();
        $req = "SELECT *FROM succursal WHERE nom='" . $nom . "'";
        $rs = $con->query($req);
        if ($rs->fetch()) {
            return true;
        } else {
            return false;
        }
    }

    public function add()
    {
        if($this->existe($this->nom)){
            return "succursal existe !!";
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public static function listerParAgent($id_agent)
    {
        $con=self::connection();
        $req="select *from succursal where id_agent=:id_agent";
        $stmt=$con->prepare($req);
        $stmt->execute(array(":id_agent"=>$id_agent));
        return $stmt->fetchAll(\PDO::FETCH_CLASS,__CLASS__);
    }

}